### ISSUE TITLE
Meeting hours and invitation

### ISSUE THREAD

**Issue by hasanbalci** [Ulkudas/2D.Sword-Shield#2]
- Please decide 2 more hours to meet (on a different day from the current one), because we want students to meet at least 4 hours per week. Write your additional hours as a comment below so that I can update the project groups page. 

- Also Invite the instructor and me to your repository as collaborators.

**Comment by Ulkudas** [comment]
Hello,

I already invited you and the instructor on github.
Here is the link: https://github.com/Ulkudas/CS-319-Group-2D/invitations

Enes

Best Regards



2018-02-08 15:18 GMT+03:00 Hasan Balcı <notifications@github.com>:

**Comment by ugurdogrusoz** [comment]
Hello?

**Comment by Eren-Aslanturk** [comment]
I think we have solved this issue but did not reassign it to you

**Comment by ugurdogrusoz** [comment]
@hasanbalci please verify and close

**Comment by hasanbalci** [comment]
Please, can you invite me and the instructor as a colloborator to your repository again. Because, I didn't get a direct email from Github itself about your invitation, while I got direct invitation emails from other repositories. Just you have sent the link of the invitation but it says "Sorry, we couldn't find that repository invitation" when I click on it.
