### ISSUE TITLE
Create a Google doc for meeting logs

### ISSUE THREAD

**Issue by ugurdogrusoz** [Ulkudas/2D.Sword-Shield#3]
and make sure the instructor and the TA has read access to it. Also make sure README.md has a link to it. You will update this doc as you meet.

**Comment by ugurdogrusoz** [comment]
Hello?

**Comment by Eren-Aslanturk** [comment]
We also forgot to comment here and let you know we added it to README.md.

You can access and comment by using this link: https://docs.google.com/document/d/1TY8qfcd7igCWaMIbnMuDU9hblguLguCGirJW7cZSaCw/edit?usp=sharing
