### ISSUE TITLE
Rename repo

### ISSUE THREAD

**Issue by ugurdogrusoz** [Ulkudas/2D.Sword-Shield#4]
as 2D.\<project name\>

**Comment by ugurdogrusoz** [comment]
@Ulkudas @Eren-Aslanturk @smoiler @akinizer When you have addressed an issue, you should assign it back to the creator for them to verify and close the issue.

**Comment by ugurdogrusoz** [comment]
Hello, anybody there to read my comments and act accordingly? :)

**Comment by Eren-Aslanturk** [comment]
Sorry we forgot to reassign it to you @ugurdogrusoz
